baseURL = 'https://danielmillward.com/'
languageCode = 'en-us'
title = 'Daniel Millward'
theme = "dmCustomTheme"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 1
  [[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 2

[taxonomies]
  category = 'categories'
  tag = 'tags'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true